### PR TITLE
add dbc support with demo in main function

### PR DESCRIPTION
**Pull request by kunalpanda**

### CODE REVIEW

**Comment by danielljeon** [comment]
# Notes

## Feedback
Don't just copy paste your previous code into the `main()` function... Please at least consider some of the application work already written.

Do not hard code the application, this is bad practice and does not support the purpose of the application being a GUI based application.
- Filters should not be hardcoded, there's already built filters for bus connections, see `CANBusManager` class structure in `bus_manager_class.py`.
- Do not hardcode a DBC filepath unless specifically identified as a test case or dev code. If so keep commented and mark with a `TODO` comment.

This code does not show any future support or consideration for #3. Given how essential DBC importing is for decoding there should be some consideration for this future enhancement.

Do not add new packages unless actually necessary. I'm not exactly sure, but I think you are using a potentially conflicting package to `python-can`. If you do add one, make sure to update the `requirements.txt`.

Make sure you comply with out conventions: [Python Code Conventions](https://github.com/OntarioTechRacing/embedded/blob/main/conventions/python.md).

## Recommendation
Recommendation is to close PR and restart. No proven compatibility and lack of proper coding practices.

**Comment by kunalpanda** [comment]
can-tools is used for dbc handling in previous versions of the code as PCAN-Basic does not support dbc files

**Comment by danielljeon** [comment]
> can-tools is used for dbc handling in previous versions of the code as PCAN-Basic does not support dbc files

The current package in use is `python-can`. There are better lightweight packages that support DBC importing and direct decoding, ie: `canmatrix` which is compatible with `python-can`'s `Message` class structure.

**Comment by kunalpanda** [comment]
The recommended changes have been implement, please review.

**Comment by danielljeon** [comment]
As previously stated:

> If you do add one [python package], make sure to update the requirements.txt.

> Make sure you comply with out conventions: [Python Code Conventions](https://github.com/OntarioTechRacing/embedded/blob/main/conventions/python.md).
- Code styling (line length).
- Missing doc strings.
- Comment / documentation styling issue.
- Missing python typing.
- Unused import call in `main.py`.
- Recommending you use black formatter as specified in conventions.

Run a static analyzer, all modern IDEs have some form of static analyzer and import optimizer.

Additionally, filters are already implemented at the hardware level. If a software post processing filter is added it should be handled as a listener or a single function.

**Comment by kunalpanda** [comment]
The filter is set to be a global array to allow adding or removing of filters dynamically using buttons in the GUI. All other recommendations have been accommodated.

**Comment by danielljeon** [comment]
> Additionally, filters are already implemented at the hardware level. If a software post processing filter is added it should be handled as a listener or a single function.

My current filter logic offloads to the hardware, which is significantly more efficient. Loading it on software might affect performance. Also if it is in software as I said before, it should be handled by the threaded Notifier and listener setup which I personally think will be better for performance. It also simplifies simulating CAN messages received using a scheduler.

**Comment by danielljeon** [comment]
Closed due to incoming full app integrated solution.

**Pull request closed without merging**
